# Generated by Django 3.2.4 on 2021-06-05 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_compra', models.FloatField()),
                ('valor_venda', models.FloatField()),
                ('quantidade', models.IntegerField()),
                ('categoria_id', models.IntegerField()),
                ('fornecedor_id', models.IntegerField()),
            ],
        ),
    ]
