# Generated by Django 3.2.4 on 2021-06-05 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciaProdutos', '0003_auto_20210605_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoVendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaProdutos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('produto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerenciaProdutos.produto')),
            ],
        ),
    ]
